### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by ddeakes** [MenelicSoftware/cordova-plugin-brother-label-printer#15]
When I try to build my iOS Cordova app after installing this plugin I now get the following error.

Any help would greatly be appreciated.

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

xcodebuild: Command failed with exit code 65

**Comment by DigvijayJaswal** [comment]
Even i am facing the same issue

**Comment by arcadius** [comment]
@ddeakes  and @DigvijayJaswal , please which command did you use to install the plugin?

Maybe you have pulled from the wrong branch?

Please make sure you use `cordova plugin add https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer --save`

**Comment by ddeakes** [comment]
@arcadius Thanks for the reply, that however still gives the same error when trying to run:

cordova build ios --save

I get:

ld: symbol(s) not found for architecture x86_64
clang: error
: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DigvijayJaswal** [comment]
@ddeakes  i was able to make it work by adding **libc** inside Linked Libraries
<img width="748" alt="Screenshot 2019-06-19 at 11 46 26 AM" src="https://user-images.githubusercontent.com/31501454/59741264-22e2b080-9288-11e9-9f05-7b1356e4efd8.png">

**Comment by sanarm123** [comment]
duplicate symbol '_kDeviceType' in:
   cordova-plugin-bxlbgatedevice/libMPosSDK.a(BxlDeviceObject.o)
  BRPtouchPrinterKit.framework/BRPtouchPrinterKit(deviceSearchByBonjour.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Not able to build, could you please help us resolve.

**Comment by robr2112** [comment]
@sanarm123, Seems the problem here is that you are using 2 SDKs from different printer vendors and each SDK has the same duplicate symbol. One or the other SDK will likely have to change the name of the constant to avoid this problem. Can you provide your contact info and I will reach out to you outside of GitHub to discuss further.

**Comment by vanerleo** [comment]
Getting the same error : `Undefined symbols for architecture x86_64:`
 whats the fix?

**Comment by robr2112** [comment]
@vanerleo It seems from other answers above that the fix is to add libc++ as a linked library. Have you tried that?

**Comment by vanerleo** [comment]
@robr2112 the only way i found to fix this is to add
```
        <framework src="libstdc++.dylib" /> 

```
plugins/cordova-plugin-brother-label-printer/plugin.xml
on line 90

**Comment by vanerleo** [comment]
@robr2112 
When using IOS emulator should `findPrinters` return printer attached to the Host MAC via USB?

**Comment by robr2112** [comment]
@vanerleo, No, I would not expect simulator to find USB-connected printers. It might find using Ethernet if you're looking for a cable-based setup.

**Comment by vanerleo** [comment]
when building a release version getting an error 
```
building for iOS Simulator, but linking in object file built for iOS, file 'Plugins/cordova-plugin-brother-label-printer/BRPtouchPrinterKit.framework/BRPtouchPrinterKit' for architecture arm64
```
any solutions for this?

**Comment by robr2112** [comment]
@vanerleo, sorry I'm not sure. Sounds like a build system issue. Have you tried doing a "clean" or "rebuild all"? Or deleting "Derived Data" for your app?

**Comment by robr2112** [comment]
@vanerleo Have you solved this yet? Are you using Xcode 12 by any chance? I just ran into a similar problem with Xcode 12.0.0. Problem doesn't happen with Xcode 11.6. Haven't tried 12.0.1 yet to see if it fixes this, but doesn't seem likely. The following StackOverflow post may provide an answer. I'm still reviewing this myself. https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios

**Comment by vanerleo** [comment]
@robr2112 using Xcode Version 12.1 (12A7403)

**Comment by robr2112** [comment]
@vanerleo OK, refer to the StackOverflow post I mentioned before. This is a new problem with Xcode12, which you will typically encounter when you build for Simulator in the Release configuration (which creates a Universal Binary, i.e. "Build Active Architecture Only" = NO). You may not have the problem when building for Debug configuration....unless you want to use a simulator that has arm64 processor...since Debug configuration will typically not try to create a UB. The SO post describes some ways to fix this for "Release" configuration by modifying the "Excluded Architectures" setting to exclude arm64 when building for Simulators. 

I have verified that this does work, at least on a Native iOS project using only Xcode and not Cordova. I don't know how to resolve this in Cordova dev environment, as I am not a Cordova developer.

-Rob

**Comment by robr2112** [comment]
@vanerleo, great that you could fix by moving to Ionic-Capacitor. Not sure why Cordova is not working? But at least you found a solution.

About the iOS13.8+ problem with WIFI Search:
I know that iOS14+ **requires** adding new settings for Bonjour Services to the Info.plist to allow search.
Didn't know this (may have) started at 13.8.

Please add the following information in the Info.plist:

1) Privacy – Local Network Usage Description 
* NOTE: IMO, this is optional only to **customize** the default system message if you want, but Apple might require it. Anyway, Apple now requires users to "opt in" to "Local Network" usage in Apps, for user privacy concerns.

2) Bonjour services (This is what will enable Search to work again)
- _pdl-datastream._tcp
- _printer._tcp
- _ipp._tcp

**Comment by arcadius** [comment]
closing as @vanerleo managed to get it working
