### ISSUE TITLE
iOS SDK version 3.1.1 is old

### ISSUE THREAD

**Issue by robr2112** [MenelicSoftware/cordova-plugin-brother-label-printer#18]
At a quick glance, it seems that your main change with this fork was to add iOS capability to the original plugin. I was wondering which version of the iOS SDK you used, since the documentation doesn't mention it. (Hint: Please add info about this).

After reviewing the info.plist in the SDK Framework, it seems you are using v3.1.1, which is old (May 2017). 

*** The latest version is v3.1.10 (April 2019), which compared to 3.1.1 has added support for several newer printer models, including RJ-4230B, RJ-4250WB, and TD-4550DNWB.

So, I am only suggesting that you should update this plugin to use the latest SDK.

Beware: iOS SDK v3.1.10 is now packaged as a "Dynamic" framework instead of a "Static" framework. All previous versions were Static. The Dynamic framework requires apps to "Add it to Embedded Binaries and Linked Frameworks and Libraries of your application target". So, your plugin will likely require a change to some settings to handle this. While this change is easy using Xcode, I don't know the details currently for how to change this inside the plugin package.

NOTE: I work for Brother Mobile Solutions.

**Comment by arcadius** [comment]
Hello @robr2112 
Thank you very much for reporting the outdated framework.
We are not sure when, but we will look into upgrading as soon as the needs arises.
We would be happy to accept contributions ... so feel free to raise a pull request.

@robr2112 , as your work for Brother, there is a question I would like to raise.
In order to test, we currently have to purchase a physical Brother Label Printer.
This makes it difficult for a developer to buy multiple printers just for testing purpose.
do you provide a "Brother Label Printer Emulator"?
This will help developers a lot.

Thank you very much

**Comment by robr2112** [comment]
About your question:
Sorry, we do not have an emulator.
Instead, I’d recommend that you sign up for our FREE “basic” developer program.
https://developerprogram.brother-usa.com/

We can provide FREE units for development/testing for a LIMITED period of time.
Ultimately, this will be much better for you than an emulator anyway.

**Comment by arcadius** [comment]
Thank you very much @robr2112  for the link.
I will register.

**Comment by arcadius** [comment]
@robr2112 , are you familiar with raising a pull request for the framework upgrade?

**Comment by arcadius** [comment]
@robr2112 , are you familiar with raising a pull request for the framework upgrade?

**Comment by robr2112** [comment]
@arcadius,  As I mentioned on the other issue, I'm a little familiar with Pull Request, but not exactly sure why I would need to do this, as you should be able to update the SDK and integrate it. Both iOS and Android SDKs are updated and released somewhat regularly. So, this should be monitored.
