### ISSUE TITLE
Bluetooth Issue

### ISSUE THREAD

**Issue by cpgb85** [MenelicSoftware/cordova-plugin-brother-label-printer#43]
When scanning for bluetooth printers, i get a system dialog popup with the list.  If I search using the method "findPrinters" it refers to bluetooth printers like they should popup in the array and not in a system dialog box. This is not the case.  Nothing happens with bluetooth.  Is this normal?

**Comment by robr2112** [comment]
Looking at the latest code in this plugin for iOS:
* "findPrinters" is only calling "findNetworkPrinters", and the bluetooth code is commented out. So, I would not expect to find BT printers with this current code.
* "findBluetoothPrinters" will return a list of "already connected" printers, or if none are currently connected it will show the iOS system dialog that allows "pairing".

So, it sounds like your printer is not connected to your iOS device, since you are seeing the system dialog.

If it IS connected and still NOT showing up in the list, then the problem is likely that you have not added the MFi protocol string to your info.plist. If this hasn't been added to your plist, then connected printers will not show up. For Brother printers, this MFi protocol string is "**com.brother.ptcbp**".

NOTE: Beware that if you support MFi printers in your app (as evidenced by this Protocol String in your info.plist), you are required to acquire a PPID (Product Plan ID) and list this in your AppStore submission notes; otherwise your app will be REJECTED by Apple. Each MFi device manufacturer will have a different process. The Brother process begins here:
https://secure6.brother.co.jp/mfi/Top.aspx

-Rob

**Comment by cpgb85** [comment]
Food for thought.  Thanks for the response. This is why the app stores are broken. So many random rules and restrictions that most devs don't know about.

**Comment by arcadius** [comment]
BlueTooth is now working on iOS.
I have tested this on QL820NWB

PR: https://github.com/MenelicSoftware/cordova-plugin-brother-label-printer/pull/48

New plugin version is 1.6.0
